### ISSUE TITLE
Exception while parsing invoice

### ISSUE THREAD

**Issue by ryzizub** [fusion44/dart_bolt11_decoder#4]
Found issue that this library will fail to decode invoice (which is valid)
```
lnbc11p3l8hmnpp5fszjygxclu4v8lk9aqwentt8yku9fw23leqsagd824dtgxkhdk5sdqqcqzzgxqyz5vqrzjqwnvuc0u4txn35cafc7w94gxvq5p3cu9dd95f7hlrh0fvs46wpvhdut0l0wdgvxeu5qqqqryqqqqthqqpyrzjqw8c7yfutqqy3kz8662fxutjvef7q2ujsxtt45csu0k688lkzu3ldut0l0wdgvxeu5qqqqryqqqqthqqpysp5sfddfymd22vyr6fq00hxay5nu0qjjhfeu73kft95yvyq7zgksems9qypqsqgnlqghe7e60u00p0gseghk779fc837r74k9l5wwpyh9thdr847j55r9kgqae6yc829atajeaps998sr2vdrzyrjqywh7anvxm6ewzrgqasp0t5
```

Exception
```
Unhandled Exception: FormatException: Could not parse BigInt
#0      _BigIntImpl.parse (dart:core-patch/bigint_patch.dart:169:7)
#1      BigInt.parse (dart:core-patch/bigint_patch.dart:52:19)
#2      new Rational.parse
rational.dart:79
#3      new Decimal.parse
decimal.dart:19
#4      Bolt11PaymentRequest._processAmount
pay_request.dart:68
#5      new Bolt11PaymentRequest
```

**Comment by ryzizub** [comment]
Should be fixed in next release

**Comment by fusion44** [comment]
@ryzizub v1.0.2 published to pub. Thank you again!
