### ISSUE TITLE
Error Decoding Invoice

### ISSUE THREAD

**Issue by anipy1** [fusion44/dart_bolt11_decoder#9]
I encountered an issue while decoding an invoice using the package. Here's how I encountered the problem:

I created an invoice for 1200 sats for the mutinynet faucet service using: https://www.lnurlpay.com/refund@lnurl-staging.mutinywallet.com

The invoice looks like: lntbs12u1pnkjenxpp5sdlwncg2d3e7tzlwl638f9czlekwdx5pc2yfuf4uwmzsvzrlx8rqhp5w6epex2vama4way8ag0j3la9uf52l9snehtm3mqldxzadz8zru3qcqzzsxqyz5vqrzjqf67k3zsf4fm9gyrs5hrhl7vfctcr9de23kpvfvsmrpg9uldxfplcq795vqqz3qqq5qqqqlgqqqqqqqqfqsp5a3jt25kxfspzenz7y483259z4z5u5xcclf4y8aml5wr3s3xqyujs9p4gqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqysgq6ajh8mjac800hr2ggzga8t9r5rm525hwyvrz09tseuahst7jk5xh3umyktn280tqdza3qs6kdngrs0tdg2q92fq0474rrqxjt80j23cqy5lamp

I used the `Bolt11PaymentRequest` class from the package to decode this invoice. However, I encountered the following error:

```
Error: FormatException: s12 is not a valid format,
Stacktrace:
#0 Rational.parse (package:rational/rational.dart:92:7)
#1 Decimal.parse (package:decimal/decimal.dart:41:51)
#2 Bolt11PaymentRequest._processAmount (package:bolt11_decoder/src/pay_request.dart:68:26)
#3 new Bolt11PaymentRequest (package:bolt11_decoder/src/pay_request.dart:42:5)
#4 InputCubit.parseInput (package:bijli/bloc/input/input_cubit.dart:65:36)
```

This error seems to occur when parsing the amount field in the invoice. Let me know if additional details are needed to reproduce or debug the issue.

**Comment by anipy1** [comment]
@fusion44 I cloned the package locally and added it to my flutter project. It looks like the above error is already fixed, but I think you haven't pushed this version to pub.dev. Anyways, this is not an issue with the code.
